/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Star wars - Episode I - Jedi Power Battles)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800629ECu
#define func_800629EC BootEntry  /* alias */
